include:
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_left
    extra-modules: [ "${ZEPHYR_BASE}/../config/zmk-pointing" ]
  - board: nice_nano_v2
    shield: splitkb_aurora_corne_right
    extra-modules: [ "${ZEPHYR_BASE}/../config/zmk-pointing" ]
