manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: zmk-pointing
      url-base: https://github.com/zmk-pointing
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pointing
      remote: zmk-pointing
      revision: main
      path: modules/zmk-pointing # Erzwingt einen sauberen Pfad
  self:
    path: config
