name: Draw ZMK keymap
on:
  workflow_dispatch:
  push:
    paths:
      - "config/splitkb_aurora_corne.keymap"

jobs:
  draw:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Wichtig fÃ¼r das Schreiben ins Repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install keymap-drawer
        run: pip install keymap-drawer

      - name: Draw keymap
        run: |
          mkdir -p img
          keymap parse -z config/splitkb_aurora_corne.keymap > config/corne.yaml
          keymap draw config/corne.yaml > img/splitkb_aurora_corne.svg

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add img/splitkb_aurora_corne.svg
          git commit -m "Update keymap image [skip ci]" || exit 0
          git push
