uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      # Gar keine spezifischen Pfade angeben, die Action sucht nach config/*.keymap
      amend_readme: true # Das versucht sogar, den Link direkt in dein README zu schreiben
